const ReduxActionTypes = {
  INIT_APP: "INIT_APP",
  INIT_SESSION_SAGA: "INIT_SESSION_SAGA",
  INIT_POLLING_SAGA: "INIT_POLLING_SAGA",
  //Session
  FETCH_SESSION_INIT: "FETCH_SESSION_INIT",
  FETCH_SESSION_SUCCESS: "FETCH_SESSION_SUCCESS",
  SELECT_SESSION : "SELECT_SESSION",
  DESELECT_SESSION: "DESELECT_SESSION",
};

export default ReduxActionTypes;
