const ReduxActionTypes = {
  INIT_APP: "INIT_APP",
  INIT_SESSION_SAGA: "INIT_SESSION_SAGA",
  //Session
  FETCH_SESSIONS_INIT: "FETCH_SESSION_INIT",
  FETCH_SESSIONS_SUCCESS: "FETCH_SESSION_SUCCESS",
  FETCH_SESSION: "FETCH_SESSION",
  FETCH_SESSION_SUCCESS: "FETCH_SESSION_SUCCESS",
  SELECT_SESSION: "SELECT_SESSION",
  DESELECT_SESSION: "DESELECT_SESSION",
  FETCH_SESSION_TEXT_LOG: "FETCH_SESSION_TEXT_LOG",
  FETCH_SESSION_TEXT_LOG_SUCCESS: "FETCH_SESSION_TEXT_LOG_SUCCESS",
  FETCH_SESSION_DEVICE_LOG: "FETCH_SESSION_DEVICE_LOG",
  FETCH_SESSION_DEVICE_LOG_SUCCESS: "FETCH_SESSION_DEVICE_LOG_SUCCESS",
  FETCH_SESSION_DEBUG_LOG: "FETCH_SESSION_DEBUG_LOG",
  FETCH_SESSION_DEBUG_LOG_SUCCESS: "FETCH_SESSION_DEBUG_LOG_SUCCESS",
  SET_SESSION_FILTER: "SET_SESSION_FILTER",
  DELETE_SESSION: "DELETE_SESSION",
  //polling
  POLLING_INIT: "POLLING_INIT",
  POLLING_STOP: "POLLING_STOP",
  ADD_POLLING_TASK: "ADD_POLLING_TASK",
  REMOVE_POLLING_TASK: "REMOVE_POLLING_TASK",
};

export default ReduxActionTypes;
